### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by arcturus23** [0xf17/vm-project-status#118]

**Comment by rjsnh1522** [comment]
need favicon image

**Comment by prakhar0** [comment]
Can use VM logo W/O text, available in Xd Files

**Comment by rjsnh1522** [comment]
complete.

**Comment by arcturus23** [comment]
![Favicon](https://user-images.githubusercontent.com/29840330/67977112-6c330b80-fc3d-11e9-8e47-9047cc425d6c.png)
- From prakhar, Please update this @rjsnh1522

**Comment by arcturus23** [comment]
@rjsnh1522 Pawan, please use the updated icon provided by Prakhar. The Icon/Logo used without background looks very dark on dark themes
