### ISSUE TITLE
Empty States 

### ISSUE THREAD

**Issue by arcturus23** [0xf17/vm-project-status#72]

**Comment by rjsnh1522** [comment]
what is this empty states about.
Please clarify

**Comment by arcturus23** [comment]
@rjsnh1522 
![Screenshot 2019-10-30 at 3 45 33 PM](https://user-images.githubusercontent.com/29840330/67849310-61d51c80-fb2c-11e9-8b50-da86a8f5d3b2.png)

Include provided images and remove default images

**Comment by arcturus23** [comment]
This is the same one as #5 which is in in Progress.
