### ISSUE TITLE
Finalise server

### ISSUE THREAD

**Issue by arcturus23** [0xf17/vm-project-status#89]
- [x] Decide server
- [x] Create and purchase server (Prakhar)
- [x] Forward the account details to Rishi

Do not share credentials here. Share privately/Slack.

**Comment by prakhar0** [comment]
Athen will be providing DO credentials over the weekend. One time payment of server credits will be done by us and will be compensated in project payment.

**Comment by prakhar0** [comment]
This is done. Pawan has required information
